---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: dagger-helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: dagger-repo
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: dagger
