package:
  name: hello-server
  version: 0.2.0
  description: friendly little webserver
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - name: Build Go application
    runs: |
      CGO_ENABLED=0 go build -ldflags "-s -w -X main.Version=${{package.version}}" -o "${{targets.destdir}}/usr/bin/hello-server" .